spring.application.name=LeetCall

server.port=8080

spring.profiles.active=local


spring.datasource.username=root
spring.datasource.password=Ankit@123+
spring.datasource.url=jdbc:mysql://localhost:3306/leetcall
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}
